# Generated by Django 3.1.1 on 2020-11-16 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
