# Generated by Django 3.1.1 on 2020-11-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201117_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.TextField()),
            ],
        ),
    ]
