# Generated by Django 3.1.1 on 2020-11-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_popup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_popup',
        ),
    ]
